[General]
bypass-system = true
ipv6 = false
prefer-ipv6 = false
private-ip-answer = true
dns-server = 
fallback-dns-server = system
dns-fallback-system = false
dns-direct-system = false
dns-direct-fallback-proxy = false
skip-proxy = 192.168.0.0/16,10.0.0.0/8,localhost,*.local,captive.apple.com,sequoia.apple.com,seed-sequoia.siri.apple.com,yiqun.io,127.0.0.1
tun-excluded-routes = 10.0.0.0/8,100.64.0.0/10,127.0.0.0/8,169.254.0.0/16,192.0.0.0/24,192.0.2.0/24,192.88.99.0/24,192.168.0.0/16,198.51.100.0/24,203.0.113.0/24,224.0.0.0/4,255.255.255.255/32,239.255.255.250/32,localhost
tun-included-routes = 
always-real-ip = localhost
icmp-auto-reply = true
always-reject-url-rewrite = false
udp-policy-not-supported-behaviour = REJECT
update-url = https://shadowrocket.yiqun.io/main.conf


[Proxy Group]
ç¬¬å››èŒƒå¼ = select,policy-regex-filter=èŒƒå¼|4paradigm|4pd
æ¾³æ´² = url-test,policy-regex-filter=ğŸ‡¦ğŸ‡º|æ¾³å¤§åˆ©äºš|æ¾³æ´²|AU,url=http://cp.cloudflare.com/generate_204,interval=600,tolerance=30,timeout=5
æ—¥æœ¬ = url-test,policy-regex-filter=ğŸ‡¯ğŸ‡µ|æ—¥æœ¬|JP,url=http://cp.cloudflare.com/generate_204,interval=600,tolerance=30,timeout=5
å°æ¹¾ = url-test,policy-regex-filter=ğŸ‡¹ğŸ‡¼|å°æ¹¾|TW,url=http://cp.cloudflare.com/generate_204,interval=600,tolerance=30,timeout=5
ç¾å›½ = url-test,policy-regex-filter=ğŸ‡ºğŸ‡¸|ç¾å›½|US,url=http://cp.cloudflare.com/generate_204,interval=600,tolerance=30,timeout=5
é¦™æ¸¯ = url-test,policy-regex-filter=ğŸ‡­ğŸ‡°|é¦™æ¸¯|hk,url=http://cp.cloudflare.com/generate_204,interval=600,tolerance=30,timeout=5


[Rule]
# ç¬¬å››èŒƒå¼
IP-CIDR,172.28.4.0/24,ç¬¬å››èŒƒå¼,no-resolve

# æ¾³æ´²
## poe
DOMAIN-SUFFIX,poe.com,æ¾³æ´²

# æ—¥æœ¬
# å°æ¹¾
# ç¾å›½
# é¦™æ¸¯
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/GitHub/GitHub.list,é¦™æ¸¯
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/YouTube/YouTube.list,é¦™æ¸¯
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Google/Google.list,é¦™æ¸¯

FINAL,DIRECT



# åŸå§‹
## AU
RULE-SET,https://shadowrocket.yiqun.io/rule/apple_news.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/AppleNews/AppleNews.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/TikTok/TikTok.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Amazon/Amazon.list,DIRECT
## JP
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Nintendo/Nintendo.list,DIRECT
## HK
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Netflix/Netflix.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Disney/Disney.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/HBO/HBO.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Spotify/Spotify.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Telegram/Telegram.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/PayPal/PayPal.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Twitter/Twitter.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Facebook/Facebook.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Steam/Steam.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Sony/Sony.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Epic/Epic.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/SteamCN/SteamCN.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Game/Game.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Microsoft/Microsoft.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/TVB/TVB.list,DIRECT
## Direct
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Apple/Apple.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/BiliBili/BiliBili.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/NetEaseMusic/NetEaseMusic.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Baidu/Baidu.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/DouBan/DouBan.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/WeChat/WeChat.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/DouYin/DouYin.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Sina/Sina.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Zhihu/Zhihu.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/XiaoHongShu/XiaoHongShu.list,DIRECT
# LAN
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Lan/Lan.list,DIRECT


[Host]
# åŸŸåæŒ‡å®šæœ¬åœ°å€¼
localhost = 127.0.0.1
# åŸŸåæŒ‡å®šDNSæœåŠ¡å™¨
*.apple.com = server:system
*.cdn-apple.com = server:system
*.icloud.com = server:system


[URL Rewrite]
[MITM]
